### ISSUE TITLE
Include contents as argument in popstate event

### ISSUE THREAD

**Issue by MoOx** [MoOx/pjax#10]
https://github.com/defunkt/jquery-pjax/pull/401

**Comment by BehindTheMath** [comment]
@MoOx We don't have a user-facing `popstate` event, as opposed to jquery-pjax, which exposes a `pjax:popstate` event. So this issue isn't relevant to us.

Unless you mean that we should implement that event as well.

**Comment by MoOx** [comment]
Not sure what I was really thinking in 2014 :D
