### ISSUE TITLE
DOMException in switchElementsAlt when copying <head> attributes

### ISSUE THREAD

**Issue by robinnorth** [MoOx/pjax#103]
The new `switchElementsAlt` switch method throws a `DOMException` for me when trying to copy `<head>` attributes:

`
DOMException: Failed to execute 'setNamedItem' on 'NamedNodeMap': The node provided is an attribute node that is already an attribute of another Element; attribute nodes must be explicitly cloned.
`

Cloning the attribute node before setting it on `oldEl` when switching resolves this issue.

**Comment by BehindTheMath** [comment]
Fixed by #104.
