### ISSUE TITLE
Minify pjax.js

### ISSUE THREAD

**Issue by BehindTheMath** [MoOx/pjax#108]
We should add a minified version of `pjax.js` to the NPM package, to reduce the bandwith required for anyone linking to it directly (using unpkg.com).

**Comment by jimaek** [comment]
jsDelivr can auto-minify css and js files. Check it out http://cdn.jsdelivr.net/npm/pjax@0.2.4/pjax.min.js

**Comment by BehindTheMath** [comment]
Cool. Maybe we should suggest this for the unminified version as well, instead of Unpkg.

**Comment by MoOx** [comment]
Can be added to npm package, but imo should not be versionned (can quickly become a pain to maintain). You can exclude with gitignore but include with npm package.json/files section.

**Comment by BehindTheMath** [comment]
>but imo should not be versionned
Do you mean it shouldn't be committed to Github?

**Comment by MoOx** [comment]
Exactly.
