### ISSUE TITLE
Check that pjax run scripts when going back in history

### ISSUE THREAD

**Issue by MoOx** [MoOx/pjax#11]
https://github.com/defunkt/jquery-pjax/pull/400

**Comment by BehindTheMath** [comment]
@MoOx jquery-pjax said about that PR that they're
>not interested in supporting various edge-cases that come with inline script execution.

Besides, shouldn't this be already covered by [execute-scripts](https://github.com/MoOx/pjax/blob/ca61c4a8402f5159065326d48b14b25bce5d277d/lib/execute-scripts.js)?

**Comment by MoOx** [comment]
Maybe...? :D
