### ISSUE TITLE
Question: Doesn't this library have the feature that invoke manual pjax?

### ISSUE THREAD

**Issue by venzersiz** [MoOx/pjax#130]
Hi, I'm using defunkt/jquery-pjax. but this library has bug. Then I am replacing spa library.

I read the document fully. But I can't find that feature. Would you help me?

**Comment by BehindTheMath** [comment]
You can use `pjax.loadUrl()`.

**Comment by venzersiz** [comment]
@BehindTheMath That method have two params. How do I set options parameter? If only href parameter set, error occurred.

Would you guide me the document or code example?

**Comment by BehindTheMath** [comment]
The second parameter is an options object. You can pass in `pjax.options`, but you will need to make sure `options.requestOptions` exists. For example:

    if (!pjax.options.requestOptions) {
        pjax.options.requestOptions = {};
    }
    pjax.loadUrl(href, pjax.options);

**Comment by BehindTheMath** [comment]
@robinnorth What do you think about falling back to `this.options` if the options parameter is not set, as well as setting `options.requestOptions = {}` in `parseOptions()`? This way, `pjax.loadUrl(href)` will just work out of the box.

**Comment by venzersiz** [comment]
@BehindTheMath Thank you very much!

**Comment by BehindTheMath** [comment]
Related: #127

**Comment by robinnorth** [comment]
@BehindTheMath yes, that sounds good to me. Per my comment in #129, I think `options.requestOptions` should be split out into a separate property that is just handled internally by the library.
