### ISSUE TITLE
'success' event not fired after manual pjax invoking.

### ISSUE THREAD

**Issue by venzersiz** [MoOx/pjax#131]
**My code**

var pjax = new Pjax({
    selectors: ['#pjax-container'],
    cacheBust: false
});

In this case events fired
1. complete event fired
2. success event fierd

But
pjax.options.requestOptions = pjax.options.requestOptions || {};
pjax.loadUrl(url, pjax.options);

In this case event fired
1. complete event fired

Is this flow right?
or Did I made a mistake?

Thx.

**Comment by robinnorth** [comment]
Have you checked to see if `pjax:error` is being fired instead? Pjax always triggers either `pjax:sucess` or `pjax:error` when triggering `pjax:complete`.

**Comment by BehindTheMath** [comment]
@venzersiz Are you still having this issue?

**Comment by venzersiz** [comment]
@BehindTheMath Oh, I made a mistake. The cause was jQuery pjax I've used has same name event handler. There isn't the problem.
