### ISSUE TITLE
'contains' method's error

### ISSUE THREAD

**Issue by venzersiz** [MoOx/pjax#135]
# CODE

`function contains(doc, selectors, el) {
  for (var i = 0; i < selectors.length; i++) {
    var selectedEls = doc.querySelectorAll(selectors[i])
    for (var j = 0; j < selectedEls.length; j++) {
      if (selectedEls[j].contains(el)) {
        return true
      }
    }
  }`

# Situations

I coded that invoke manual pjax call on `<select>` element's change event. And then doc.querySelectorAll line in code above, occurred error.

# Error message

Uncaught TypeError: doc.querySelectorAll is not a function

# Parameters in debug

doc = ["pjax-container"]
selectors = select#category_sel
el = undefined

Did I mistake?
Thank you!

**Comment by BehindTheMath** [comment]
@venzersiz Can you post the complete stack trace?

**Comment by venzersiz** [comment]
pjax.js:981 Uncaught TypeError: doc.querySelectorAll is not a function
    at contains (pjax.js:981)
    at Pjax.loadContent (pjax.js:133)
    at Pjax.<anonymous> (pjax.js:202)
    at XMLHttpRequest.request.onreadystatechange (pjax.js:780)

**Comment by BehindTheMath** [comment]
You're right, that's a bug.

On [this line](https://github.com/MoOx/pjax/blob/f98f2dd63b48113ff91b6bd8808257bfc723ef6b/index.js#L131):
```
if (document.activeElement && contains(this.options.selectors, document.activeElement)) {
```
should be:
```
if (document.activeElement && contains(document, this.options.selectors, document.activeElement)) {
```
