### ISSUE TITLE
determine if content in a pjax container is changed or not 

### ISSUE THREAD

**Issue by cpetro** [MoOx/pjax#149]
If I use the default behaviour of pjax, with no switches , only the new (additional) content appears to load, and any existing content that is already on the page  just stays where it is, this is good but it cannot be animated

is there a way to animate only the new content , and leave the existing content in its place unless it is being removed/ changed? how can I create a new switch callback to do this ? is there a way to know if the content in a container has changed or not , and if it has then only animate the the new content and leave the old

**Comment by BehindTheMath** [comment]
There's no way out of the box to know which content has been switched, unless you create your own switch and keep track.

If you just want to animate the new content, create your own switch and do it there. Take a look at the [README](https://github.com/MoOx/pjax#switches-object-default-) for how to do that.

**Comment by BehindTheMath** [comment]
Closing due to lack of follow-up from OP.
