### ISSUE TITLE
about history and loadUrl not effective

### ISSUE THREAD

**Issue by jcleng** [MoOx/pjax#151]
useing 
`var pjax = new Pjax({
                    selectors: ["body"],
                    history: true
                });`
the history not effective,and 
`
pjax.loadUrl("3.html", {
                    requestOptions: {
                        timeout: 200
                    },
                });
`
useing pjax.loadUrl without history

**Comment by BehindTheMath** [comment]
The `history` option is `true` by default; there's no need to set it manually.

What are you trying to accomplish?

**Comment by jcleng** [comment]
@BehindTheMath i will trying to accomplish this:
`pjax.loadUrl("3.html", { requestOptions: { timeout: 200 }, });` and to change my history with browser,but ,loadUrl without changge browser history . maybe is my problem,?

**Comment by jcleng** [comment]
@BehindTheMath notworking

**Comment by BehindTheMath** [comment]
The history under the back button stays the same?

Try cloning the repo, and run `npm run example` in the console. Click one of the button on the example page and check if the history changes.

**Comment by jcleng** [comment]
@BehindTheMath but i not useing npm ,useing `<script src="https://cdn.jsdelivr.net/npm/pjax/pjax.min.js"></script>`,can't working for this?

**Comment by BehindTheMath** [comment]
Can you check the console in the browser and see if there are any errors?

**Comment by jcleng** [comment]
@BehindTheMath 0 errors,maybe rewrite source code
