### ISSUE TITLE
[Enhancement] Google Tag Manager

### ISSUE THREAD

**Issue by Malvoz** [MoOx/pjax#154]
How would I go about modifying the current [pjax.min.js](https://cdn.jsdelivr.net/npm/pjax/pjax.min.js) from having the currently integrated Analytics code to [Google Tag Manager](https://developers.google.com/tag-manager/quickstart) instead?

Google is now recommending GTM over Analytics, could we have an example of such integration?

**Comment by BehindTheMath** [comment]
I've never used GTM. Can you post the code you're currently using?

**Comment by Malvoz** [comment]
@BehindTheMath 

https://developers.google.com/tag-manager/quickstart
> 
> <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
> new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
> j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
> 'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
> })(window,document,'script','dataLayer','GTM-XXXX');</script>
>

**Comment by BehindTheMath** [comment]
I don't mean the initialization code from Google. I mean the code you use to actually log events. Similar to the `ga()` function for Google Analytics. What are the function calls? When are they called? What type of data do you pass to them?

The Pjax's `analytics` function is called after all switches finish, right after the `pjax:complete` and `pjax:success` events are tiggered (see [here](https://github.com/MoOx/pjax/blob/7d26a75fdfe4a8c24ff479612ea9a563ea72a81f/index.js#L216)). If all you want to do is log the page view, you can override that function by doing something like:

    pjax.options.analytics = function() {
        // Your code here
    }

You can see [here](https://github.com/MoOx/pjax/blob/7d26a75fdfe4a8c24ff479612ea9a563ea72a81f/lib/parse-options.js#L34-L40) how the default function for Google Analytics works.

Alternatively, you can add an event handler for those events and put your code there.

**Comment by Malvoz** [comment]
I'm not using pjax in production, and the initialization code from Google is the only code I've used in other projects, with GTM you instead add events in your account within the GTM interface.

**Comment by BehindTheMath** [comment]
Closing due to lack of follow-up from OP.
