### ISSUE TITLE
Pjax switch fail

### ISSUE THREAD

**Issue by bihac** [MoOx/pjax#161]
Hi. I got this error on a part of my website. 
"Pjax switch fail: Dom doesn't look the same on new loaded page 'title' new 0, old 1"

I have checked both pages title's and they are the same. How can i fix this issue?

**Comment by BehindTheMath** [comment]
Please post a CodePen demonstrating the issue. If that's not feasible, please post the original HTML, the raw response from the HTTP call, and your Pjax configuration.

**Comment by bihac** [comment]
Main Page:


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="example" />
    <meta name="keywords" content="example" />
    <meta name="robots" content="index,follow"/>
    <meta name="googlebot" content="all"/>
    <meta name="revisit-after" content="1 Days"/>
    <meta name="distribution" content="global"/>
    <meta name="rating" content="general"/>
    <meta name="author" content="example"/>
    <title>Example site</title>
    <link rel="shortcut icon" href="/favicon.ico"/>
    
    <link href="/template/radyo/css/bootstrap.min.css" rel="stylesheet">
	/* style files */
</head>
<body>

/* HTML*/


<li>
                    <a href="/example-news" title="caption" class="category-list_item ic-url">
                        <div class="image col-4">
                            <img src="news-image.jpg" alt=" Manga Akdamar'ın Hikayesini Ele Aldı">
                        </div>
                        <div class="news-info col-8">
                            <div class="news-title"> caption</div>

                            <div class="shortly"> shortly...</div>
                            <div class="news-date"><i class="fa fa-clock"></i> date</div>
                        </div>

                    </a>
                </li>

/*HTML*/


<script type="text/javascript" src="/template/radyo/js/jquery.min.js"></script>
<script type="text/javascript" src="/template/radyo/js/popper.min.js"></script>
<script type="text/javascript" src="/template/radyo/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/template/radyo/pjax/pjax.min.js"></script>
<script>
$(function () {

 var pjax = new Pjax({
        elements: "a.ic-url",
        selectors: ["title", "#main-content","#scripts"],
        cacheBust :false,
    });
    document.addEventListener('pjax:send', displayLoader);
    document.addEventListener('pjax:success', hideLoader);
})
</script
<div id="scripts" style="display: none">
    </div>

</body>
</html>



News Page: 


<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="example" />
    <meta name="keywords" content="example" />
    <meta name="robots" content="index,follow"/>
    <meta name="googlebot" content="all"/>
    <meta name="revisit-after" content="1 Days"/>
    <meta name="distribution" content="global"/>
    <meta name="rating" content="general"/>
    <meta name="author" content="example"/>
    <title>Example site</title>
    <link rel="shortcut icon" href="/favicon.ico"/>
    
    <link href="/template/radyo/css/bootstrap.min.css" rel="stylesheet">
	/* style files */
</head>
<body>

/* HTML*/

</body>
</html

**Comment by bihac** [comment]
There is a real time web site. You can see there.

http://radyo.comu.edu.tr

Every pjax request success but in the bottom of main page there are news (HABERLER) you can see. When i click any news link in chrome console it says : "Pjax switch fail: Dom doesn't look the same on new loaded page 'title' new 0, old 1".

**Comment by bihac** [comment]
and there is pjax call:

var pjax = new Pjax({
        elements: "a.ic-url",
        selectors: ["title", "#main-content","#scripts"],
        cacheBust :false,
    });

    document.addEventListener('pjax:send', displayLoader);
    document.addEventListener('pjax:success', hideLoader);

**Comment by bihac** [comment]
There are youtube videos in news pages as iframe. Is this may caused that?

**Comment by BehindTheMath** [comment]
It looks to me that the issue is being cause since one of your selectors is for the `title` tag, but the new page doesn't have such a tag.

**Comment by bihac** [comment]
I m looking the both pages source code in chrome. Both have same tags including title tag.  Even check when error occoures ajax response html. There is <title> tag inside <head> tag. Can you check please. I couldnt even stop page load when error occoured. How can i stop page load to see console log?

**Comment by bihac** [comment]
Sorry my bad. There was an issue on server side catching ajax actions thats why there was no title. Thanks again
