### ISSUE TITLE
Needs popstate option to resolve history issue

### ISSUE THREAD

**Issue by sleddd** [MoOx/pjax#170]
If you use whenDOMReady and try hitting the back button, it won't fire using success | complete. To get whenDOMReady to fire when navigating with history (back | forward), you need to attach an event listener to popstate. (i.e. document.addEventListener('pjax:popstate', function(){ //do stuff });

If you alter the pjax library within the function that handles popstate at about line 53 with:
trigger(document,"pjax:popstate", state.options)

Then you will be able to add in your custom code: 
document.addEventListener('pjax:popstate', whenDOMReady)

It will solve the DOM ready, etc... not firing on history issue. 

I would suggest adding the pjax:popstate option...

**Comment by BehindTheMath** [comment]
What's wrong with the success or complete events?

**Comment by sleddd** [comment]
Popstate is handled in main Pjax constructor (var  Pjax = function), however success and complete are handled in option of the Pjax.prototype - this means popstate won’t always/if ever hit the trigger for success/complete. jquery-pjax has same issue, but they offer popstate, so it solves any history bugs with that.

I learned this the hard way, because I had a website it caused issues for when re-initing DOM ready functions in success | end. At first, we were using jquery-pjax which had popstate, so it was fine, but then we needed multi-selectors and we saw your library, which is awesome btw!, and switched, however that old history issue popped up and I realized you needed the popstate option, so I added it :) 

I know other people will have similar issues as they do with jquery-pjax (until they figure out to use popstate in conjunction with success | end), so I thought I would let you know that you might want to add that.

- Claudette

**Comment by BehindTheMath** [comment]
The `popstate` handler calls `loadUrl()` to load the page, just like when you click a new link. Further down the callstack, the `pjax:success` and `pjax:complete` events should be triggered.

**Comment by sleddd** [comment]
They aren't that's why I added it,  but if you don't want to add it to the main library, or adjust the success/complete, so it does trigger on popstate then that's fine. I can just keep it with my own.

However, it is important to note that popstate, success, and complete are all states it is helpful to be able to add an event listener for.. and i'm sure others could use that option as well.

**Comment by BehindTheMath** [comment]
I don't understand the issue. Popstate should trigger the success and complete events. Did you try it and it wasn't triggered?

**Comment by sleddd** [comment]
Unfortunately, no, it was not triggered in every instance...

**Comment by BehindTheMath** [comment]
Please post your code that reproduces the issue, so I can try to debug it.

**Comment by sleddd** [comment]
All I can tell you, is that it does not always trigger with success/complete and reliably works with popstate. Thank you for your help, but I have resolved my issue.
