### ISSUE TITLE
New release o'clock ?

### ISSUE THREAD

**Issue by Geolim4** [MoOx/pjax#172]
Hello,

The history bug #164 is blocking, is it possible to release a new version of the lib ?

Thanks you very much !

**Comment by BehindTheMath** [comment]
I still don't understand why you would want to disable history.

Regardless, if you need this fix now, use `npm install moox/pjax` to install the latest code from Github.

**Comment by Geolim4** [comment]
Because of SEO purpose on forms for one of our customer that requested to not have GET parameters visible in URL. I'm as annoyed as you. But it's his request and we just have to comply with it :/

**Comment by Geolim4** [comment]
Why did you closed this issue while there's still no new release ATM ?

Not everyone use npm...

**Comment by BehindTheMath** [comment]
There is no point in keeping this issue open. The release will come when it's ready and someone has time to work on it. I provided an option that can be used in the meantime. If you don't want to install it with npm, you can download the code from Github and build it yourself.

**Comment by Geolim4** [comment]
My environment does not let me to use npm nor building it by myself since
this project makes use of a CDN which follows your releases (this is a LTE
project). This is why I'm such a pain in your ass :)

**Comment by BehindTheMath** [comment]
v0.2.7 has been released.

**Comment by Geolim4** [comment]
Thanks you very much 😘
