### ISSUE TITLE
Ignoring some scripts in <head>

### ISSUE THREAD

**Issue by nanook21** [MoOx/pjax#175]
Hi,

Is there a way to set a selector on "head" but to prevent certain scripts from being re-run on a new page load?

Andrew

**Comment by BehindTheMath** [comment]
Use a global variable to store whether the scripts were run already, then check that value in your scripts.

**Comment by nanook21** [comment]
Unfortunately that won’t work in my setup as there are some CMS scripts
that I don’t have access to modify.

I was hoping that there might be a way to specify class IDs to ignore
within the head?

**Comment by BehindTheMath** [comment]
There's no built in way to do that. Your bet bet is to move the script tag outside of any elements affected by Pjax.

**Comment by nanook21** [comment]
For others who might be interested, I was able to put together a workaround by adding this line of code below:

```
  loadContent: function(html, options) {
    // ADDED below line to strip items with the 'no-pjax' class name from the HTML:
    html = html.replace(/<.* class=(\'|\")no-pjax(\'|\")[^\0]*?\/.*>/g, '');
```

**Comment by BehindTheMath** [comment]
[Re parsing HTML using regex](https://stackoverflow.com/a/1732454/8037425). 😄
