### ISSUE TITLE
Change way to handle .isSupported

### ISSUE THREAD

**Issue by MoOx** [MoOx/pjax#18]
Currently the way things are (shitty) done, the trick to "mock" api for unsupported browser is awful cause you can for eg use Pjax.switches.blah.
After refactor on testling branch, I need to do something else.
Like just add a .isSupported method & document the fact that every call & ref usages should be prefixed by this test ?

**Comment by BehindTheMath** [comment]
@MoOx Do we still need to support browsers that don't support the History API? According to [caniuse](https://www.caniuse.com/#search=history), nearly 95% of browsers in use support it.

In my opinion, we should just have 1 check for `isSupported()` in the constructor before doing anything, and then make the user responsible for implementing a fallback.

**Comment by MoOx** [comment]
2014, I guess we can just forget this.
