### ISSUE TITLE
run scripts after pjax load

### ISSUE THREAD

**Issue by nicdnepr** [MoOx/pjax#192]
why pjax not runs scripts after load page?
for example in page footer script alert
after pjax load alert not fired
if click f5 then alert fired

**Comment by BehindTheMath** [comment]
Please post a codepen showing the issue.

**Comment by nicdnepr** [comment]
here test code
```
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>The HTML5 Herald</title>
  <meta name="description" content="The HTML5 Herald">
  <meta name="author" content="SitePoint">

  <script src="https://cdn.jsdelivr.net/npm/pjax/pjax.js"></script>


</head>

<body>
  
  <div id='content'>
      page 1
  <a href='2.html' ajaxLink>page 2</a>
  </div>
  <div id='footer'></div>
  
  <script>
  new Pjax({
  elements: 'a[ajaxLink]',
  selectors: ['#content'],
})
  </script>
</body>
</html>

```
2.html
```
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>The HTML5 Herald</title>
  <meta name="description" content="The HTML5 Herald">
  <meta name="author" content="SitePoint">

  

</head>

<body>
  <div id='content'>page 2</div>
  <div id='footer'>
  <script>alert('load');</script>
  </div>
</body>
</html>

```

**Comment by nicdnepr** [comment]
any ideas?

**Comment by BehindTheMath** [comment]
I don't see any issues with the above code. The alert shows for me after clicking the link.

**Comment by BigGitWorld** [comment]
@BehindTheMath 
I run the above code but the alert did not called!
How did you run it with alert?

**Comment by BehindTheMath** [comment]
I'm sorry, but I can no longer help with this. This issue is from almost 2 years ago, and I haven't used this library in almost that long.

**Comment by BigGitWorld** [comment]
Your welcome.
Please can you tell me what version you have used?
I have serious problems with the latest version. I want to use it in my SPA project but <script> tags are not called. while I see in the ajx (xhr) response, I have <script> tags. 
I opened a new issue but nobody help me and I don't know how do I have to solve it :(
