### ISSUE TITLE
Please fix your bundle

### ISSUE THREAD

**Issue by aolko** [MoOx/pjax#193]
Your bundle is broken, index(.min).js still reuires scripts from the `lib` folder, which does not exist.
Also getting this error
![](https://i.imgur.com/pe9s99K.png)

**Comment by BehindTheMath** [comment]
Did you read the README? You should be using pjax.js or pjax.min.js.

index.js is not a bundle.

**Comment by fjeddy** [comment]
`pjax.js`and `pjax.min.js` doesnt exist, and the readme doesn't specifically mention it, so it's quite understandable that he gets confused.

**Comment by BehindTheMath** [comment]
I'm not sure what you mean. The package on npm includes both of those files (see [here](https://cdn.jsdelivr.net/npm/pjax/)). The Github repo does not, but I don't see anywhere in the README suggesting you clone the repo.

**Comment by fjeddy** [comment]
And what about those that don't use NPM? Which is quite a few people.

**Comment by BehindTheMath** [comment]
The README gives clear instructions how to use a script tag with the CDN link, and it says quite clearly to use either pjax.js or pjax.min.js.

**Comment by fjeddy** [comment]
And yet again, your making assumptions that anyone want's to use a third party cookie collecting CDN. Like I said, I get his confusion, i ditched the entire library myself due to how you do things.

**Comment by BehindTheMath** [comment]
The only way I can think of to get the library without using the CDN or npm is by cloning from Github. I'm not sure why you feel the CDN uses cookies and Github does not, or why it's better to copy from Github than the CDN.

Regardless, such an installation method is never mentioned in the README, so it's a bit presumptuous to do it and them complain when it doesn't work. I can add instructions for building from the source, but I think this is the first time someone has mentioned having an issue with this.

**Comment by fjeddy** [comment]
99% don't mention it, they just move on to the next thing.
