### ISSUE TITLE
ctrl + mouse click

### ISSUE THREAD

**Issue by nicdnepr** [MoOx/pjax#195]
how enable ctrl+left mouse click?
to open new tab with link

**Comment by nicdnepr** [comment]
Any ideas?

**Comment by MoOx** [comment]
Should work already https://github.com/MoOx/pjax/blob/2c6506af65e23a1aa256b0c00dddc39590a3a088/lib/proto/attach-link.js#L40
poke @BehindTheMath

**Comment by nicdnepr** [comment]
I checked, ctrl+mouse click not work

**Comment by BehindTheMath** [comment]
@nicdnepr Please link to a demo showing the issue.

**Comment by nicdnepr** [comment]
http://pjax.awa.pp.ua/catalog/Attenjuatory
need click on any product selected link with ctrl+clik
![2019-02-12-115253_1920x1080_scrot](https://user-images.githubusercontent.com/2581487/52626901-dc85db00-2ebc-11e9-8e78-7ea33f79f60a.png)

**Comment by BehindTheMath** [comment]
The link didn't work even after I removed the Pjax listener. So I'm not sure that it's an issue with Pjax.

Try removing the `ajaxlink` attribute, and see if the link works.

**Comment by BehindTheMath** [comment]
And btw, that's not such a simple site. You might benefit from using a bigger library like Vue.

**Comment by nicdnepr** [comment]
I removed `ajaxlink` and ctrl+click started work
Can you check the problem?

**Comment by nicdnepr** [comment]
Any ideas?

**Comment by nicdnepr** [comment]
Can somebody help?

**Comment by BehindTheMath** [comment]
This library is not currently being actively maintained. If you're having issues, you might want to look for something else.

**Comment by BehindTheMath** [comment]
This does not appear to be an issue with Pjax. When you click one of those links, the Pjax handler is not invoked, so it's not Pjax that is handling the click.

**Comment by nicdnepr** [comment]
Sorry men but I really need this library
It only has functions I need
Please help me!

**Comment by nicdnepr** [comment]
If I remove pjax, ctrl+click starts work
