### ISSUE TITLE
scrollTo work only first time

### ISSUE THREAD

**Issue by nicdnepr** [MoOx/pjax#197]
After first click page srolls to top
Second click don't scroll top

**Comment by nicdnepr** [comment]
http://pjax.awa.pp.ua/catalog/Transljacionnye-usiliteli-mo%C5%A1%C4%8Dnosti
scroll down and click paging 2 times
![2019-02-12-145754_1920x1080_scrot](https://user-images.githubusercontent.com/2581487/52637007-b836f800-2ed6-11e9-8e5c-6d2a5de80335.png)

**Comment by BehindTheMath** [comment]
That page doesn't load for me.

**Comment by nicdnepr** [comment]
Its impossible, url opens
Can you check on local server scrollTo for links in case links reloaded with pjax?

**Comment by nicdnepr** [comment]
Any alive?

**Comment by BehindTheMath** [comment]
When you click on one of the page numbers, Pjax run its handlers and afterwards a jQuery handler runs and makes the same request, which replaces the links and the Pjax handlers. You can check in devtools and see how after you click one of the links, the exact same request is made by Pjax and then jQuery, and then the Pjax attributes and handlers disappear. I can't spend hours debugging your site, bit it does not appear to be an issue with Pjax.

Like I mentioned [before](https://github.com/MoOx/pjax/issues/195#issuecomment-463036445), this is a complex site, using jQuery and multiple instances of Pjax. This isn't really the use case Pjax was designed for, and I strongly suggest you use a library like Vue instead.

**Comment by nicdnepr** [comment]
Thanks for idea about jquery, I fixed this issue
But what about idea about #195
Not sure if problem with jquery
