### ISSUE TITLE
Dynamic Selectors - Not exists at all pages

### ISSUE THREAD

**Issue by royshoa** [MoOx/pjax#204]
I am using the Pjax at the navigation menu and switching some selectors at the page. My issue is that there is a class that exists only at the website homepage and I like Pjax to add it when the user browses to the homepage and remove it when the user browses to another page. 

Are there is a way to do it without bypass the Pjax object?

**Comment by Buliwyfa** [comment]
It will be nice to add some fallbacks selectors like on falsandtru/pjax-api (falsandtrucall the selectors areas) http://falsandtru.github.io/pjax-api/
