### ISSUE TITLE
add keyboard support

### ISSUE THREAD

**Issue by MoOx** [MoOx/pjax#23]

**Comment by BehindTheMath** [comment]
@MoOx Can you give some more details?

**Comment by MoOx** [comment]
The idea will be to use keyboard to navigate to a link and be sure that hitting "enter" does the pjax behavior (make even more sense for form validated with enter)

**Comment by BehindTheMath** [comment]
It looks like this is already covered:

https://github.com/MoOx/pjax/blob/d3d5ef7a11186d2da717e5a5beb503b38f8df2d8/lib/proto/attach-link.js#L88-L90

https://github.com/MoOx/pjax/blob/d3d5ef7a11186d2da717e5a5beb503b38f8df2d8/lib/proto/attach-form.js#L91-L93

**Comment by MoOx** [comment]
Feel free to close if that's working then :)
