### ISSUE TITLE
adding title to selectors results in full page loading

### ISSUE THREAD

**Issue by BigGitWorld** [MoOx/pjax#231]
This is my simple pjax code:
```
 var pjax = new Pjax({
        selectors: [
            "title",
            "#content-main"
        ]
    });
```
If ``title`` does not exist in the above code, everything work fine (title of page does not change).
But If I add ``title`` to the ``selectors`` (such as the above), I have a full page loading!

My DOM is same and I can use [jquery-pjax](https://github.com/defunkt/jquery-pjax) lib successfully. 

what is the problem?

**Comment by piperhaywood** [comment]
@BigGitWorld I’m running in to a similar issue and can’t seem to figure out what’s going on, were you able to sort this out?

**Comment by piperhaywood** [comment]
Just adding a followup: I think the issue may have been an embed on the page, perhaps Pjax is detecting multiple titles? At any rate, I added a class to the `<title>` tag like so: `<title class="site-title">` and then used the selector `title.site-title` in the options and this seemed to clear it up.
