### ISSUE TITLE
add form support

### ISSUE THREAD

**Issue by MoOx** [MoOx/pjax#25]

**Comment by gurre** [comment]
+1

**Comment by gaillafr** [comment]
+1

**Comment by eatonphil** [comment]
+1

**Comment by Flobin** [comment]
Agreed, this would be really sweet. What is needed to make this happen? Is it about adding the form contents to the request?

**Comment by BehindTheMath** [comment]
@MoOx @lacrioque
Is this fixed by 86e5a22?

**Comment by MoOx** [comment]
No idea. Looks like it should be.

**Comment by BehindTheMath** [comment]
Fixed by 86e5a22.
