### ISSUE TITLE
abort previous pjax request when several requests are made by a crazy person clicking everywhere

### ISSUE THREAD

**Issue by MoOx** [MoOx/pjax#27]

**Comment by howells** [comment]
Is there a way to handle this right now? Having this issue!

**Comment by MoOx** [comment]
Nope. It's not really easy to cancel xhr request.
Are you the crazy person? :D

**Comment by howells** [comment]
Ha *maybe*! No it's just a client request. No worries will try and find a workaround.

**Comment by MoOx** [comment]
Feel free to make a PR if you find a solution!

**Comment by robinnorth** [comment]
Fixed in #114
