### ISSUE TITLE
Save scroll position in navigation history

### ISSUE THREAD

**Issue by madaboutbrighton** [MoOx/pjax#30]
Great project! You have a scroll option, which is useful for when NEW content is loaded.

However, if i do the following:
- visited a link
- scrolled down the page
- clicked on a new link
- viewed the new page
- hit the back button

I am taken to the top of the page again. So i have to scroll all the way back down, trying to find where i was before.

When i click a link, can pjax not record my scroll position before loading the new content, then when i go back to a page, take me back to the same scroll position?

This would be very helpful.

Thanks very much.

**Comment by darylteo** [comment]
I believe #40 is related to this.

**Comment by BehindTheMath** [comment]
@MoOx Would it be possible to implement this by storing the scroll position along with the state when calling `pushState()`?

**Comment by MoOx** [comment]
Probably?
