### ISSUE TITLE
Example for jsScroll / infinate scroll

### ISSUE THREAD

**Issue by madaboutbrighton** [MoOx/pjax#31]
I see that you intend to add a few demos...

Would it be possible to add a demo which uses [jsScroll](http://jscroll.com/) or a similar infinite scroll add-on?

This is because i cannot see how to get this to work with your pjax.

Thanks very much!!

**Comment by BehindTheMath** [comment]
@MoOx I don't think it makes sense to extend Pjax to cover such a use case. Like you said, Pjax is for replacing existing content with new content, not adding content.

**Comment by MoOx** [comment]
Agree
