### ISSUE TITLE
Example Project?

### ISSUE THREAD

**Issue by granicus422** [MoOx/pjax#37]
Do you have an example project that shows, in the simplest manner possible, how to set up a webpage to use this project?

I am new to the pjax concept, as well as require.js, and there seem to be a lot of intermediate steps missing that describe how to set up your require calls in order to correctly load and call the pjax project's dependencies.  A simple example project with two html pages showing the basic pjax loading functionality would answer all these setup questions.

Thank you.

**Comment by MoOx** [comment]
This library is commonjs only (browserify, webpack).
If you want to use it in another env (amd, global) you will need to build a standalone build (using `browseirfy --standalone Pjax index.js > Pjax.js`)

**Comment by granicus422** [comment]
Thank you.  That was the exact information I needed.  I find this library to be much more flexible than jquery-pjax, and making a standalone build of 0.1.4 works perfectly.
