### ISSUE TITLE
HierarchyRequestError

### ISSUE THREAD

**Issue by graup** [MoOx/pjax#39]
Hi, I tried using the latest version but it breaks on a HierarchyRequestError. I tracked down the bug:

[Here](https://github.com/MoOx/pjax/blob/6eafcf8dc61742adfb0bc7a0f401a849366f1422/index.js#L139) you call `trigger(document, ...)`, but trigger will add the element to the DOM if it doesn't have a parentNode (which document doesn't) [here](https://github.com/MoOx/pjax/blob/6eafcf8dc61742adfb0bc7a0f401a849366f1422/lib/events/trigger.js#L23). The result is a call like `document.body.appendChild(document)` which breaks.

After downgrading to 0.1.4 this error disappeared.

**Comment by rstacruz** [comment]
getting this too.

**Comment by Axure** [comment]
Me, too.

**Comment by MoOx** [comment]
Fix as a PR is always welcome :)

**Comment by MoOx** [comment]
Note: I don't currently use this package and so, do not want to take time for it.

**Comment by pklada** [comment]
Did this ever get fixed? Getting this too.

**Comment by MoOx** [comment]
Closed by 1d292a1a6eeb19918304c28d31b513d05a88c086

**Comment by rstacruz** [comment]
woohoo!
