### ISSUE TITLE
Add blur on active element when page is changed

### ISSUE THREAD

**Issue by MoOx** [MoOx/pjax#4]
To remove focus on a clicked/tapped link (eg on ipad, a attached tooltip can remain visible after the new page load, which is weird)

**Comment by BehindTheMath** [comment]
>Add blur on active element when page is changed
>To remove focus on a clicked/tapped link (eg on ipad, a attached tooltip can remain visible after the new page load, which is weird)

@MoOx Isn't this covered by [this line](https://github.com/MoOx/pjax/blob/3c8cd087c5352b92fb7f1090b0c39b29cfa7a31a/index.js#L132) and [this line](https://github.com/MoOx/pjax/blob/3c8cd087c5352b92fb7f1090b0c39b29cfa7a31a/index.js#L132)? I don't know why both are needed, but regardless, the focus should be lost.

>Be careful to this issue defunkt/jquery-pjax#377

This should be a simple fix, similar to what was ultimately implemented [here](https://github.com/defunkt/jquery-pjax/pull/545).

**Comment by MoOx** [comment]
You pointed the same line, but I guess you are right. Maybe I was referring to event triggered by js (eg: tooltip opened on a tap/click that should be hidden when tapping outside), can't remember...

**Comment by BehindTheMath** [comment]
Sorry. I meant [this line](https://github.com/MoOx/pjax/blob/3c8cd087c5352b92fb7f1090b0c39b29cfa7a31a/index.js#L132) and [this line](https://github.com/MoOx/pjax/blob/3c8cd087c5352b92fb7f1090b0c39b29cfa7a31a/index.js#177).
