### ISSUE TITLE
Could you update the example? It's not working

### ISSUE THREAD

**Issue by OliverZ** [MoOx/pjax#48]
I can't run the example code correctly.

The browser Console Shows (Firefox 43.0.1)

````
GET 
http://localhost:3000/pjax.js [HTTP/1.1 404 Not Found 2ms]
Document initialized: "http://localhost:3000/index.html" example.js:2:1
ReferenceError: Pjax is not defined
````
same behavior also in Internet Explorer 11.

I did the following commands:

````
git clone "https://github.com/MoOx/pjax.git"
cd pjax
node -v
v5.3.0
npm i
npm i -g serve
npm run example
> pjax@0.2.1 example C:\Development\temp\pjax
> echo '
==> Open http://localhost:3000/example in your browser.'; serve .

'

     (nothing served yet)
cd example
serve .
````
After that, I opened `http://localhost:3000/index.html` in the browser window, opened the console window and saw the errormessage I already posted above `...ReferenceError: Pjax is not defined...`

**Comment by OliverZ** [comment]
the above error can be fixed after adjusting the file paths. But then I got the following error: `HierarchyRequestError: Node cannot be inserted at the specified point in the hierarchy pjax.js:283:0`

**Comment by MoOx** [comment]
So it's #39
