### ISSUE TITLE
[Proposal] Manual invocation of Pjax.

### ISSUE THREAD

**Issue by darylteo** [MoOx/pjax#54]
A static method that allows invocation instead of relying on declarative options. 

This would open the door to things like
- dynamic links (instead of relying on href), could be based on runtime vars like time or attributes
- non-a links
- non-click (mobile taps, hovers, keypresses)
- or any number of processing steps to yield a target url to load
- different switch options

This method could also return a Promise, and puts us closer to $.pjax.

**Comment by MoOx** [comment]
:+1:

**Comment by darylteo** [comment]
Need a bit more thought on this... looking at the code it doesn't seem like pjax was designed to have multiple instances of pjax instantiated on the same page. I ... might be trying to use this library wrongly =) I'll leave it for 0.3.0 maybe, but due to time constraints I'll rethink the way I'm using it.

**Comment by BehindTheMath** [comment]
@darylteo Can't you accomplish this by calling `pjax.loadUrl()`?

**Comment by darylteo** [comment]
@BehindTheMath this was 2 years ago. Can't remember. Feel free to close =)
