### ISSUE TITLE
No X-PJAX header in request

### ISSUE THREAD

**Issue by intositeme** [MoOx/pjax#58]
It works, but the request header looks like it's missing the X-PJAX header, trying to setup my backend to just return body content for pjax request.

**Comment by darylteo** [comment]
@intositeme yup! I mentioned this in another issue and will put it in the next release.

**Comment by MoOx** [comment]
The point of this plugin is that you should not need it, since this plugin can work without any server change.

**Comment by darylteo** [comment]
I think there might be merit in partial loads as a progressive optimisation step. Some people might be coming from jquery.pjax (hence the need for containers). I defer decision to you of course (and I haven't yet had the need for it at present in this project).

**Comment by intositeme** [comment]
Oh so @darylteo will you be implementing it?
It'll be handy to have, since then i can set my server to just return necessary content and not html headers etc.

I'm using Laravel with it, and it has a built in method that particularly checks for the header https://laravel.com/api/5.2/Illuminate/Http/Request.html#method_pjax

**Comment by darylteo** [comment]
@intositeme i'm just a contributor. As I don't need it at present I won't be spending any time on it (I'm on company time so I can't justify it sorry)

**Comment by BehindTheMath** [comment]
The X-PJAX header has been added by #80.

However, there is currently no implementation for a partial load feature.
