### ISSUE TITLE
installing failed via npm install pjax on visual studio to umbraco solution 

### ISSUE THREAD

**Issue by Ben-TangentDesign** [MoOx/pjax#61]
I've just tried to install this within Visual Studio for an Umbraco Install and I get the following output:
![error](https://cloud.githubusercontent.com/assets/12425975/12672437/2b9ce6b2-c66e-11e5-9a2c-c62b0194df41.jpg)

No files or folders are added to the solution and re running the instal produces the same result. 

was expecting the following folder to be added "/node_modules/pjax"

**Comment by darylteo** [comment]
There is a open issue for updating the npm build to the latest functional version (0.2.2). Just need to wait for @MoOx to get to it as he's got the npm credentials.

**Comment by MoOx** [comment]
@Ben-TangentDesign can you try with latest version? (0.2.2)

**Comment by vrmontes** [comment]
I get the error too:

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "pjax"
npm ERR! node v5.5.0
npm ERR! npm  v3.8.1

npm ERR! No compatible version found: pjax
npm ERR! Valid install targets:
npm ERR! 0.2.2, 0.2.1, 0.2.0, 0.1.4, 0.1.3, 0.1.2, 0.1.1, 0.1.0
npm ERR!

**Comment by MoOx** [comment]
@vrmontes you are not getting the same error.
What command did you enter to install pjax?

**Comment by vrmontes** [comment]
Hi, i used:
npm install pjax

On ubuntu 14.04

**Comment by MoOx** [comment]
I fixed this. I messed up latest tag. Should be ok now.

**Comment by vrmontes** [comment]
Thanks
