### ISSUE TITLE
Accessing the anchor that was clicked before pjax:send

### ISSUE THREAD

**Issue by howells** [MoOx/pjax#62]
Hi - wonder if anyone could help me, I need to somehow access the anchor that was actually clicked to trigger the pjax:send event. I figured I could do this by listening for the click on any <a> but this event happens _after_ the pjax:send. Any ideas?

**Comment by darylteo** [comment]
@howells  I trigger pjax call directly.

````
$('.something').click(function(e) {
  e.preventDefault();
  var target = e.getCurrentTarget; // is what you want

  pjax.loadUrl(url, options); // triggers pjax
});
````

Note that pjax has to be a singleton, or it may break history (I haven't tested it, but from code inspection it seems that pjax was designed to only be instantiated once)

**Comment by howells** [comment]
Huh that's an interesting approach yeah - thanks. Right now I overrode `Pjax.prototype.attachLink` with the same function, but prepended it with various stuff that I needed to do, which isn't really sustainable!

**Comment by BehindTheMath** [comment]
With #94, you can access the element that triggered the `pjax:send` event with `event.triggerElement`.
