### ISSUE TITLE
Question: is v0.2.2 stable/usable?

### ISSUE THREAD

**Issue by rstacruz** [MoOx/pjax#64]
I remember the latest versions were always unusable. Is this okay now? I see this message is still in the readme:

> Note: current master is WIP.
> Checkout v0.1.4 for latest "stable" (no tests so kind of funny to call that stable).

**Comment by MoOx** [comment]
Should be ok, README Is not up to date. Please let this issue open as a reminder :)

**Comment by MoOx** [comment]
I updated the readme and npm.
