### ISSUE TITLE
Looking for a MAINTAINER

### ISSUE THREAD

**Issue by MoOx** [MoOx/pjax#69]
I am not using this lib anymore. Feel free to contact me to get git write access and npm rights.

**Comment by Torann** [comment]
I hope someone takes it over for you. I just started using it and I have to say it's one of the better pjax options out there.

**Comment by darylteo** [comment]
@MoOx I'm a little interested, though not sure about my credentials and time investment.

Last time this project was in focus for me, but I'm aware you were too busy to move forward on some PRs. And at this point in time, the focus at my client project has since moved on to other agendas. 

I've seen your activity on all the postcss stuff! How do you find the time!? Appreciate your efforts =)

**Comment by MoOx** [comment]
@Torann I think pjax approach will be deprecated by stuff like react + fetch.
I made this lib for my personal website last time, but now I am making an entire engine on top of react http://phenomic.io

@darylteo I don't work that much on PostCSS, now I am involved in a new project, https://phenomic.io/ ;)
For you question, you might find an answer here https://github.com/MoOx/ama/issues/12

**Comment by darylteo** [comment]
Well I see your name popping up everywhere, that's a lot, in my book =).

Anyway, I'll tentatively put my hand up for lack of any better options (I hope you do, wouldn't wish myself on any poor project ;) ).

**Comment by andreasvirkus** [comment]
> @Torann I think pjax approach will be deprecated by stuff like react + fetch.

@MoOx I beg to differ. SSGs have been growing in popularity since ~2012 and show no signs of slowing down. This is a lovely lib to just attach to them "plug-n-play" style. I'm currently choosing an ajax nav lib...
Is this still somewhat actively maintained?

**Comment by MoOx** [comment]
>  SSGs have been growing in popularity since ~2012

Yeah I know. And I like SSGs. I even created one. See https://phenomic.io/

So no this lib is not actively maintained ;)

**Comment by andreasvirkus** [comment]
:/ Sad to hear. Best of luck with phenomic.

**Comment by lacrioque** [comment]
Stil looking for a maintainer?
I'm working at LimeSurvey and we make a lot of user from this Library.
So I'm throwing myself into the pool for maintenance.

**Comment by MoOx** [comment]
@lacrioque what your npm username?

**Comment by lacrioque** [comment]
lacrioque, like on GitHub

**Comment by MoOx** [comment]
You have been added

**Comment by MoOx** [comment]
If anyone wants to help more, feel free to ask here.
