### ISSUE TITLE
Add option to *not* cache-bust

### ISSUE THREAD

**Issue by tremby** [MoOx/pjax#70]
Requests have a timestamp added to the end at https://github.com/MoOx/pjax/blob/master/lib/request.js#L15, presumably to get around caches. I don't want to get around caches in this way, since my pages are static. It would be good to have an option to skip adding this query string.

**Comment by MoOx** [comment]
PR welcome :)

**Comment by tremby** [comment]
How do you get at the options from those lib files?

**Comment by MoOx** [comment]
https://github.com/MoOx/pjax/blob/ee530f4c0a5f4f016f03601865ce36e386a0f7b1/lib/proto/parse-options.js

**Comment by tremby** [comment]
`this.options` was the answer I was actually looking for, but that helped too -- thanks.

**Comment by tremby** [comment]
Closing in favour of pull request #71.
