### ISSUE TITLE
Exclude links with a specific class ?

### ISSUE THREAD

**Issue by cpetro** [MoOx/pjax#75]
Hi , 

Just wondering if you know a quick way to exclude link elements with certain class such as "a.no-Pjax" 

thanks for your help!

CHRIS

**Comment by oskarrough** [comment]
You could overwrite the `getElements` method. It's a function that should return a NodeList of elements. How you exclude certain elements is up to you.

```js
Pjax.prototype.getElements = function() {
  return document.querySelectorAll('.js-Pjax:not(.no-Pjax)')
}

new Pjax({})
```

**Comment by BehindTheMath** [comment]
Or you could do
```
new Pjax({
    elements: "a:not(.no-Pjax)"
})
```
