### ISSUE TITLE
Fails on Internet Explorer

### ISSUE THREAD

**Issue by drpiou** [MoOx/pjax#77]
Hi,

I have an error on Internet Explorer which falls back everytime to classical switch page with refresh.
I checked the pjax code and I saw that the function `document.implementation.createHTMLDocument` was in use with no parameters (which I also saw was optional).

But, I finally found workaround to my bug and make IE working great with pjax by simply giving an argument to `createHTMLDocument`, like `'pjax'` for example.

**Comment by lacrioque** [comment]
Thank you very much!
It is implemented now
