### ISSUE TITLE
Images fails to load because relative path is changed too late

### ISSUE THREAD

**Issue by aurimus** [MoOx/pjax#82]
I am using it on a site where the images are loaded with local path `<img src="pagename/somepath/image.jpg"/>` and what happens is that the `pagename` does not get updated even though that's what should change. Therefore images don't load.

**Comment by lacrioque** [comment]
This seems to be a design issue.
Pjax can only change dom elemtents, it will not change the pagename.
You may change that manually on pjax:complete, or try to render the images differently.
