### ISSUE TITLE
Attaching pjax to links created at runtime?

### ISSUE THREAD

**Issue by Carlows** [MoOx/pjax#88]
It seems that if I try to create a new link on the page, PJax won't work over those links and a full page reload happens instead.

Is there a way to bind PJax to links created at runtime?

**Comment by Carlows** [comment]
As a workaround for this, I'm manually binding the pjax `attachLink` function to any links created at runtime:

```
    $('.slick-cloned .episode-preview-link').each(function () {
      pjaxInstance.attachLink(this);
    });
```

**Comment by MoOx** [comment]
`pjaxInstance.refresh()` should do it
