### ISSUE TITLE
Having to include require 

### ISSUE THREAD

**Issue by Ben-TangentDesign** [MoOx/pjax#89]
Hi,

When trying to use switches I have to include the Require library in my HTML.

I then get constant file issues in node_modules.

`Uncaught Error: Module name "events/on.js" has not been loaded yet for context: _. Use require([])`

Just trying to add animation to the example in bower

**Comment by MoOx** [comment]
How are you consuming the module?

**Comment by Ben-TangentDesign** [comment]
im loading the pjax.js withing a common.js file:

then calling:
`  require(['pjax'], function(pjax){

        alert('pjax loaded');

        var p = new pjax({
          selectors: ["title", ".js-Pjax"],
          switches: {
            ".js-Pjax": require("pjax/lib/switches.js").sideBySide
          },
          switchesOptions: {
            ".js-Pjax": {
              classNames: {
                // class added on the element that will be removed
                remove: "Animated Animated--reverse Animate--fast Animate--noDelay",
                // class added on the element that will be added
                add: "Animated",
                // class added on the element when it go backward
                backward: "Animate--slideInRight",
                // class added on the element when it go forward (used for new page too)
                forward: "Animate--slideInLeft"
              },
              callbacks: {
                // to make a nice transition with 2 pages as the same time
                // we are playing with absolute positioning for element we are removing
                // & we need live metrics to have something great
                // see associated CSS below
                removeElement: function(el) {
                  el.style.marginLeft = "-" + (el.getBoundingClientRect().width/2) + "px"
                }
              }
            }
          }
        })
      });`

if i add the brackets into the require call it then asks for it be done to every .js file in the lib folder

**Comment by MoOx** [comment]
You are mixin amd with commonjs. This cannot work this way. Not sure how to handle this with amd.

**Comment by Ben-TangentDesign** [comment]
Thats fair enough. What is the recommended approach to loading? Do you just use commonjs on your website? I've tried the standalone js with nothing else and it still asks to me use require([]) on the switches.js require call.

**Comment by Ben-TangentDesign** [comment]
Even when trying to use something like the below in the example doesn't seem to work:
`new Pjax({
  selectors: ["title", ".js-Pjax"],
  switches: {
    ".js-Pjax": require("pjax/lib/switches.js").sideBySide
  },
  switchesOptions: {
    ".js-Pjax": {
      classNames: {
        // class added on the element that will be removed
        remove: "Animated Animated--reverse Animate--fast Animate--noDelay",
        // class added on the element that will be added
        add: "Animated",
        // class added on the element when it go backward
        backward: "Animate--slideInRight",
        // class added on the element when it go forward (used for new page too)
        forward: "Animate--slideInLeft"
      },
      callbacks: {
        // to make a nice transition with 2 pages as the same time
        // we are playing with absolute positioning for element we are removing
        // & we need live metrics to have something great
        // see associated CSS below
        removeElement: function(el) {
          el.style.marginLeft = "-" + (el.getBoundingClientRect().width/2) + "px"
        }
      }
    }
  }
})
`
Just never loads the switches.js correctly

**Comment by MoOx** [comment]
You should use browserify or webpack.

Note: use 3 backticks for code blocks
